install.packages('MASS')
library(readxl)
library(MASS)
library(tidyverse)
d<-read_excel("D:/新建文件夹 (5)/大三/多元统计/EX4.9.xlsx",1)
names(d)<-c('credit', 'number','X1','X2','X3','X4','X5','X6','X7','X8')
d$credit<-as.factor(d$credit)
set.seed(123)
n<-length(d[[1]])
ids<-1:n
id_tr<-sample(ids,6)
id_te<-setdiff(ids,id_tr)
d_tr<-as.data.frame(d[id_tr,-2])
d_te<-as.data.frame(d[id_te,-2])
install.packages('heplots')
library(heplots)
boxM(d_tr[,3:9],d_tr[,1])
model<-qda(credit~X1+X2+X3+X4+X5+X6+X7+X8,data=d_tr)
model2<-lda(credit~X1+X2+X3+X4+X5+X6+X7+X8,data=d_tr)
